kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: tutedude
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: aadityaa173/tutedude_devops:backend01
          ports:
            - containerPort: 5000