kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  namespace: tutedude
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: aadityaa173/tutedude_devops:frontend01
          ports:
            - containerPort: 3000