version: "3.8"

services:
  frontend:
    # build: ./frontend
    image: aadityaa173/tutedude_devops:frontend01
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: aadityaa173/tutedude_devops:backend01
    # build: ./backend
    ports:
      - "5000:5000"
  